/**
 * Created by cuss on 2018/2/6.
 */
export default {
    GET_USER: 'GET_USER',
    GET_AUTH: 'GET_AUTH',
    SET_WEIXIN_READY: 'SET_WEIXIN_READY',
    SET_USER: 'SET_USER',
    SET_AUTH: 'SET_AUTH',
    FETCH_USER_INFO: 'FETCH_USER_INFO',
    GET_WX_CONFIG_STATE: 'GET_WX_CONFIG_STATE',
    SET_EX_CONFIG_STATE: 'SET_EX_CONFIG_STATE',
    SHARE_COUNT: 'SHARE_COUNT'
}
